### ISSUE TITLE
Crash when opening cmake files

### ISSUE THREAD

**Issue by 3699394** [uyha/tree-sitter-cmake#14]
```
warning: Section `.reg-xstate/59344' in core file too small.
#0  0x00007ffff7dce830 in __GI___regexec (preg=0xbf6898, string=string@entry=0xbf6890 "#", nmatch=nmatch@entry=1, pmatch=pmatch@entry=0x7fffffffb2d0,
    eflags=eflags@entry=2) at /usr/src/debug/glibc-2.37-4.fc38.x86_64/posix/regexec.c:214
214       lock_lock (dfa->lock);
[Current thread is 1 (Thread 0x7ffff7cd7740 (LWP 59344))]
(gdb) bt
#0  0x00007ffff7dce830 in __GI___regexec (preg=0xbf6898, string=string@entry=0xbf6890 "#", nmatch=nmatch@entry=1, pmatch=pmatch@entry=0x7fffffffb2d0,
    eflags=eflags@entry=2) at /usr/src/debug/glibc-2.37-4.fc38.x86_64/posix/regexec.c:214
#1  0x00007ffff7e344ce in advance (string=0xbf6890 "#", expbuf=<optimized out>) at regexp.c:78
#2  0x00007ffff6d5b674 in scan () from /home/user/.local/share/nvim/lazy/nvim-treesitter/parser/cmake.so
#3  0x00000000006f2098 in ts_parser__lex (parse_state=1, version=<optimized out>, self=0xbf6890)
```

Experienced crash when opening cmake file in neovim. Is it because of the glibc version that I am using?

**Comment by uyha** [comment]
is this still a problem?
